FEED FORWARD NEURAL NETWORK

In [114]:
import keras 
import tensorflow
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [115]:
(xtrain,ytrain),(xtest,ytest)=mnist.load_data()

In [116]:
xtrain.shape

(60000, 28, 28)

In [117]:
xtest.shape

(10000, 28, 28)

In [118]:
xtest[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [119]:
xtrain=xtrain.reshape(60000,784).astype('float32')
xtest=xtest.reshape(10000,784).astype('float32')

In [120]:
xtrain/=255
xtest/=255

In [121]:
xtest[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [122]:
from keras import utils as np_utils
nclasses=10

In [123]:
ytrain=keras.utils.np_utils.to_categorical(ytrain,nclasses)
ytest=keras.utils.np_utils.to_categorical(ytest,nclasses)

In [124]:
model=Sequential()

In [125]:
model.add(Dense(64,activation='sigmoid',input_shape=(784,)))

In [126]:
model.add(Dense(10,activation='softmax'))

In [127]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_11 (Dense)            (None, 64)                50240     
                                                                 
 dense_12 (Dense)            (None, 10)                650       
                                                                 
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [128]:
model.compile(loss='MeanSquaredError',optimizer=SGD(learning_rate=0.01),metrics=['accuracy'])

In [129]:
model.fit(xtrain,ytrain,batch_size=40,epochs=50,verbose=1)

Epoch 1/50
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0914 - accuracy: 0.1270
Epoch 2/50
1500/1500 [==============================] - 2s 2ms/step - loss: 0.0895 - accuracy: 0.1684
Epoch 3/50
1500/1500 [==============================] - 2s 2ms/step - loss: 0.0883 - accuracy: 0.2818
Epoch 4/50
1500/1500 [==============================] - 2s 2ms/step - loss: 0.0872 - accuracy: 0.3282
Epoch 5/50
1500/1500 [==============================] - 2s 2ms/step - loss: 0.0861 - accuracy: 0.3330
Epoch 6/50
1500/1500 [==============================] - 2s 2ms/step - loss: 0.0851 - accuracy: 0.3453
Epoch 7/50
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0839 - accuracy: 0.3586
Epoch 8/50
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0827 - accuracy: 0.3735
Epoch 9/50
1500/1500 [==============================] - 2s 2ms/step - loss: 0.0815 - accuracy: 0.3885
Epoch 10/50
1500/1500 [==============================] - 2s 2ms/step - loss: 0.080

In [130]:
ypred=model.predict(xtest)

In [131]:
ypred

array([[0.01279279, 0.00449731, 0.00371776, ..., 0.8663395 , 0.00546737,
        0.06327666],
       [0.04212095, 0.02961604, 0.4378689 , ..., 0.00215414, 0.06116844,
        0.00470173],
       [0.00263797, 0.7802321 , 0.03583629, ..., 0.03104105, 0.03715032,
        0.02235748],
       ...,
       [0.00256495, 0.01387044, 0.01142787, ..., 0.07865418, 0.10162187,
        0.29744655],
       [0.05268333, 0.09864699, 0.05547094, ..., 0.06557394, 0.2575496 ,
        0.08752476],
       [0.04447795, 0.0012988 , 0.06563715, ..., 0.00098334, 0.00615691,
        0.00579448]], dtype=float32)

In [132]:
ytest

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [133]:
from sklearn.metrics import r2_score
print(r2_score(ytest,ypred))

0.6249167102466276
